spring:
  application:
    name: camel-and-boot
server:
  port: 8080
logging:
  level:
    root: info
    org.apache.camel: info
    org.springframework.boot: info
    dev.cmartin.learn: debug
    #org.hibernate.sql: debug
    #org.hibernate.type.descriptor.sql: debug
management:
  #endpoint:
  #  camelroutes:
  #    enabled: true
  endpoints:
    web:
      exposure:
        include: camel, camelroutes, info, health
camel:
  dataformat:
    jackson:
      pretty-print: true
      auto-discover-object-mapper: true